### ISSUE TITLE
When `add-upstream` fails due to merge conflicts, the merge conflicts are cleaned up instead of being left for repair

### ISSUE THREAD

**Issue by yumaikas** [PrincipleStudios/scalable-git-branching-tools#17]
There's a couple of ways I think that we could fix this.

The first is to just leave the merge conflict state as-is, which we don't currently do.

The other would be to emit a message saying to use `git merge <branch>` manually, which *might* make more sense?

**Comment by pcj02b** [comment]
I agree the message with the merge command would be the most helpful thing.
