### ISSUE TITLE
Support a `pull-upstream -recurse` functionality

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/scalable-git-branching-tools#19]
The best way to tackle merge conflicts is to make sure the upstream branches flow only to the immediate downstream branches; a flag to make `pull-upstream` be recursive would be beneficial. However, this starts getting messy in the case of merge conflicts in an upstream branch.

With the suggested solution in #17, simply providing a message that one of the upstream branches had a conflict and include that it needs to be checked out and resolved that way may be the best solution.

**Comment by krisnotchris** [comment]
I like this. Curious what a scenario would look like where we wouldn't use the flag. Seems like something I would always use.

**Comment by mdekrey** [comment]
The problem is that it could leave you on a different branch if you had conflicts, at least based on the current implementation. This would be unexpected and not very desirable.

**Comment by JordanRhode** [comment]
`pull-upstream -recurse` added in https://github.com/PrincipleStudios/scalable-git-branching-tools/pull/126
