### ISSUE TITLE
Provide mechanism to rebuild a release candidate based on its current branches with modifications

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/scalable-git-branching-tools#38]
Original suggestion from @pcj02b was to provide a `remove-upstream` function, but given that removing an upstream requires destroying any other commits in the history, this would be unwise to have alongside `add-upstream`.

Instead, I propose:
- Update the `rc` to have a switch to `-reuseUpstream` that would keep the current set
- In this scenario, `-branches` would add new branches, similar to `add-upstream`
- Add a `-withoutBranches` list of branches that would filter the final result to remove the named branches
- Display a warning if one of the `-withoutBranches` is still in the recursive upstream.

**Comment by JordanRhode** [comment]
https://github.com/PrincipleStudios/scalable-git-branching-tools/pull/116
