### ISSUE TITLE
Identifying incorrect branch names in RC command

### ISSUE THREAD

**Issue by AverageJosh** [PrincipleStudios/scalable-git-branching-tools#78]
RC command continues if a branch name does not exist within the repository. Possibly fail out the rc command explaining it can't find the branch? Or continue on leaving a message at the end (probably want to fail it)

**Comment by mdekrey** [comment]
This has been resolved with the latest rewrites/upgrades. Can you confirm, @AverageJosh?

**Comment by AverageJosh** [comment]
Confirmed this now works. Closing issue
